import './globals.css';

import AuthProvider from './auth/Provider';
import GoogleAnalyticsScript from './GoogleAnalyticsScript';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import NavBar from './NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' data-theme='winter'>
			<GoogleAnalyticsScript />
			<body className={inter.className}>
				<AuthProvider>
					<NavBar />
					<main className='p-5'>{children}</main>
				</AuthProvider>
			</body>
		</html>
	);
}
